//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace PeriodicTableWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="periodictableSoap", Namespace="http://www.webserviceX.NET")]
    public partial class periodictable : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAtomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAtomicWeightOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAtomicNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetElementSymbolOperationCompleted;
        
        /// <remarks/>
        public periodictable() {
            this.Url = "http://www.webservicex.net/periodictable.asmx";
        }
        
        /// <remarks/>
        public event GetAtomsCompletedEventHandler GetAtomsCompleted;
        
        /// <remarks/>
        public event GetAtomicWeightCompletedEventHandler GetAtomicWeightCompleted;
        
        /// <remarks/>
        public event GetAtomicNumberCompletedEventHandler GetAtomicNumberCompleted;
        
        /// <remarks/>
        public event GetElementSymbolCompletedEventHandler GetElementSymbolCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/GetAtoms", RequestNamespace="http://www.webserviceX.NET", ResponseNamespace="http://www.webserviceX.NET", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAtoms() {
            object[] results = this.Invoke("GetAtoms", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAtoms(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAtoms", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAtoms(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAtomsAsync() {
            this.GetAtomsAsync(null);
        }
        
        /// <remarks/>
        public void GetAtomsAsync(object userState) {
            if ((this.GetAtomsOperationCompleted == null)) {
                this.GetAtomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAtomsOperationCompleted);
            }
            this.InvokeAsync("GetAtoms", new object[0], this.GetAtomsOperationCompleted, userState);
        }
        
        private void OnGetAtomsOperationCompleted(object arg) {
            if ((this.GetAtomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAtomsCompleted(this, new GetAtomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/GetAtomicWeight", RequestNamespace="http://www.webserviceX.NET", ResponseNamespace="http://www.webserviceX.NET", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAtomicWeight(string ElementName) {
            object[] results = this.Invoke("GetAtomicWeight", new object[] {
                        ElementName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAtomicWeight(string ElementName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAtomicWeight", new object[] {
                        ElementName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAtomicWeight(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAtomicWeightAsync(string ElementName) {
            this.GetAtomicWeightAsync(ElementName, null);
        }
        
        /// <remarks/>
        public void GetAtomicWeightAsync(string ElementName, object userState) {
            if ((this.GetAtomicWeightOperationCompleted == null)) {
                this.GetAtomicWeightOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAtomicWeightOperationCompleted);
            }
            this.InvokeAsync("GetAtomicWeight", new object[] {
                        ElementName}, this.GetAtomicWeightOperationCompleted, userState);
        }
        
        private void OnGetAtomicWeightOperationCompleted(object arg) {
            if ((this.GetAtomicWeightCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAtomicWeightCompleted(this, new GetAtomicWeightCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/GetAtomicNumber", RequestNamespace="http://www.webserviceX.NET", ResponseNamespace="http://www.webserviceX.NET", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAtomicNumber(string ElementName) {
            object[] results = this.Invoke("GetAtomicNumber", new object[] {
                        ElementName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAtomicNumber(string ElementName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAtomicNumber", new object[] {
                        ElementName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAtomicNumber(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAtomicNumberAsync(string ElementName) {
            this.GetAtomicNumberAsync(ElementName, null);
        }
        
        /// <remarks/>
        public void GetAtomicNumberAsync(string ElementName, object userState) {
            if ((this.GetAtomicNumberOperationCompleted == null)) {
                this.GetAtomicNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAtomicNumberOperationCompleted);
            }
            this.InvokeAsync("GetAtomicNumber", new object[] {
                        ElementName}, this.GetAtomicNumberOperationCompleted, userState);
        }
        
        private void OnGetAtomicNumberOperationCompleted(object arg) {
            if ((this.GetAtomicNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAtomicNumberCompleted(this, new GetAtomicNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/GetElementSymbol", RequestNamespace="http://www.webserviceX.NET", ResponseNamespace="http://www.webserviceX.NET", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetElementSymbol(string ElementName) {
            object[] results = this.Invoke("GetElementSymbol", new object[] {
                        ElementName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetElementSymbol(string ElementName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetElementSymbol", new object[] {
                        ElementName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetElementSymbol(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetElementSymbolAsync(string ElementName) {
            this.GetElementSymbolAsync(ElementName, null);
        }
        
        /// <remarks/>
        public void GetElementSymbolAsync(string ElementName, object userState) {
            if ((this.GetElementSymbolOperationCompleted == null)) {
                this.GetElementSymbolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetElementSymbolOperationCompleted);
            }
            this.InvokeAsync("GetElementSymbol", new object[] {
                        ElementName}, this.GetElementSymbolOperationCompleted, userState);
        }
        
        private void OnGetElementSymbolOperationCompleted(object arg) {
            if ((this.GetElementSymbolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetElementSymbolCompleted(this, new GetElementSymbolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetAtomsCompletedEventHandler(object sender, GetAtomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAtomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAtomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetAtomicWeightCompletedEventHandler(object sender, GetAtomicWeightCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAtomicWeightCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAtomicWeightCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetAtomicNumberCompletedEventHandler(object sender, GetAtomicNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAtomicNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAtomicNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetElementSymbolCompletedEventHandler(object sender, GetElementSymbolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetElementSymbolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetElementSymbolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
